import Head from 'next/head';
import { API } from '../requests';

import styles from '../styles/Home.module.css';

const SignIn = () => {
  const handleSignIn = async () => {
    await API.auth.signInWithTwitter();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <button onClick={handleSignIn}>sign in with twitter</button>
      </main>
    </div>
  );
};

export default SignIn;
